axi-symmetric_steady:
  Max Output Level: 4
  Coordinate System: Axi Symmetric
  Simulation Type: Steady state
  Steady State Max Iterations: 10
  Output File: case.result

MagnetoDynamics2DHarmonic:
  Equation: MgDyn2DHarmonic
  Procedure: '"MagnetoDynamics2D" "MagnetoDynamics2DHarmonic"'
  Variable: 'Potential[Potential Re:1 Potential Im:1]'
  Variable Dofs: 2
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-5
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: BiCGStab
  Linear System Max Iterations: 1000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-7
  Linear System Abort Not Converged: True
  Linear System Residual Output: 10

MagnetoDynamicsCalcFields:
  Equation: CalcFields
  Procedure: '"MagnetoDynamics" "MagnetoDynamicsCalcFields"'
  Potential Variable: Potential
  Calculate Joule Heating: True
  Calculate Magnetic Field Strength: True
  Calculate Electric Field: True
  Calculate Current Density: True
  Calculate JxB: Logical True  
  Exec Solver: Always
  Calculate Nodal Fields: Logical False
  Calculate Elemental Fields: Logical True
  Linear System Residual Output: 10

ResultOutputSolver:
  Exec Solver: 'After timestep'
  Equation: ResultOutputSolver
  Procedure: '"ResultOutputSolve" "ResultOutputSolver"'
  Discontinuous Bodies: True
  VTU Format: True
  # VTU Part Collection: True
  Save Geometry Ids: 'Logical True'
